interface IdiomSet {
  start1: string;
  start2: string;
  end1: string;
  end2: string;
}

const idioms: IdiomSet[] = [
  {
    start1: '',
    start2: 'A fool and his money',
    end1: 'is easily parted',
    end2: 'are easily parted',
  },
  {
    start1: '',
    start2: 'Accidents',
    end1: 'happens',
    end2: 'happen',
  },
  {
    start1: '',
    start2: 'Actions',
    end1: 'speaks louder than words',
    end2: 'speak louder than words',
  },
  {
    start1: '',
    start2: 'All good things',
    end1: 'must come to an end',
    end2: 'must come to an end',
  },
  {
    start1: '',
    start2: 'All roads',
    end1: 'leads to Rome',
    end2: 'lead to Rome',
  },
  {
    start1: '',
    start2: "All the world's a stage, and all the men and women",
    end1: '',
    end2: '',
  },
  {
    start1: 'All the world',
    start2: '',
    end1: 'is a stage, and all the men and women merely players',
    end2: '',
  },
  {
    start1: '',
    start2: 'April showers',
    end1: '',
    end2: 'bring May flowers',
  },
  {
    start1: '',
    start2: 'Appearances',
    end1: 'can be deceiving',
    end2: 'can be deceiving',
  },
  {
    start1: '',
    start2: 'Barking dogs',
    end1: 'seldom bites',
    end2: 'seldom bite',
  },
  {
    start1: '',
    start2: 'Beggars',
    end1: "can't be a chooser",
    end2: "can't be choosers",
  },
  {
    start1: '',
    start2: 'Birds of a feather',
    end1: 'flocks together',
    end2: 'flock together',
  },
  {
    start1: '',
    start2: 'Boys',
    end1: 'will be boys',
    end2: 'will be boys',
  },
  {
    start1: '',
    start2: 'Cheaters',
    end1: 'never prospers',
    end2: 'never prosper',
  },
  {
    start1: '',
    start2: 'Clothes',
    end1: 'does not make the man',
    end2: 'do not make the man',
  },
  {
    start1: '',
    start2: 'Comparisons',
    end1: 'is odious',
    end2: 'are odious',
  },
  {
    start1: '',
    start2: 'Dead men',
    end1: 'tells no tales',
    end2: 'tell no tales',
  },
  {
    start1: '',
    start2: 'First impressions',
    end1: 'is the most lasting',
    end2: 'are the most lasting',
  },
  {
    start1: '',
    start2: 'Fools',
    end1: '',
    end2: 'seldom differ',
  },
  {
    start1: '',
    start2: 'God helps those who',
    end1: '',
    end2: 'help themselves',
  },
  {
    start1: '',
    start2: 'Good fences',
    end1: 'makes good neighbours',
    end2: 'make good neighbours',
  },
  {
    start1: '',
    start2: 'Good things',
    end1: 'comes to those who wait',
    end2: 'come to those who wait',
  },
  {
    start1: '',
    start2: 'Good things',
    end1: 'comes in small packages',
    end2: 'come in small packages',
  },
  {
    start1: '',
    start2: 'Great minds',
    end1: '',
    end2: 'think alike',
  },
  {
    start1: '',
    start2: 'Great minds',
    end1: '',
    end2: 'think alike, fools seldom differ',
  },
  {
    start1: '',
    start2: 'Great minds think alike, fools',
    end1: '',
    end2: 'seldom differ',
  },
  {
    start1: '',
    start2: 'Little things',
    end1: 'pleases little minds',
    end2: 'please little minds',
  },
  {
    start1: '',
    start2: 'Many drops',
    end1: 'makes a shower',
    end2: 'make a shower',
  },
  {
    start1: '',
    start2: 'Many hands',
    end1: 'makes light work',
    end2: 'make light work',
  },
  {
    start1: '',
    start2: 'Oil and water',
    end1: "doesn't mix",
    end2: "don't mix",
  },
  {
    start1: '',
    start2: 'Only fools and horses',
    end1: 'works',
    end2: 'work',
  },
  {
    start1: '',
    start2: 'Only the good',
    end1: 'dies young',
    end2: 'die young',
  },
  {
    start1: '',
    start2: '',
    end1: 'should do as the Romans do',
    end2: 'should do as the Romans do',
  },
  {
    start1: '',
    start2: 'Those who live in glass houses',
    end1: "shouldn't throw stones",
    end2: "shouldn't throw stones",
  },
  {
    start1: '',
    start2: 'Sticks and stones may break my bones, but words',
    end1: 'will never hurt me',
    end2: 'will never hurt me',
  },
  {
    start1: '',
    start2: 'Sticks and stones',
    end1: 'may break my bones, but words will never hurt me',
    end2: 'may break my bones, but words will never hurt me',
  },
  {
    start1: '',
    start2: 'The best things in life',
    end1: 'is free',
    end2: 'are free',
  },
  {
    start1: 'The eye',
    start2: 'The eyes',
    end1: 'is the window to the soul',
    end2: 'are the window to the soul',
  },
  {
    start1: '',
    start2: 'The meek',
    end1: 'will inherit the earth',
    end2: 'will inherit the earth',
  },
  {
    start1: '',
    start2: "Those who can, do; those who can't,",
    end1: '',
    end2: 'teach',
  },
  {
    start1: '',
    start2: "Those who don't learn from history",
    end1: '',
    end2: '',
  },
  {
    start1: '',
    start2: 'Those who sleep with dogs',
    end1: 'will rise with fleas',
    end2: 'will rise with fleas',
  },
  {
    start1: '',
    start2: 'Too many cooks',
    end1: 'spoils the broth',
    end2: 'spoil the broth',
  },
  {
    start1: '',
    start2: 'Two heads',
    end1: 'is better than one',
    end2: 'are better than one',
  },
  {
    start1: '',
    start2: 'Two wrongs',
    end1: "doesn't make a right",
    end2: "don't make a right",
  },
  {
    start1: '',
    start2: 'The walls',
    end1: 'has ears',
    end2: 'have ears',
  },
  {
    start1: '',
    start2: "When the cat's away the mice",
    end1: '',
    end2: 'will play',
  },
  {
    start1: '',
    start2: 'When the going gets tough, the tough',
    end1: '',
    end2: 'get going',
  },
  {
    start1: '',
    start2: 'Wonders',
    end1: 'will never cease',
    end2: 'will never cease',
  },
  {
    start1: '',
    start2: 'Worse things',
    end1: 'happens at sea',
    end2: 'happen at sea',
  },
  {
    start1: 'A bad excuse',
    start2: '',
    end1: 'is better than none',
    end2: 'are better than none',
  },
  {
    start1: 'A bad workman',
    start2: '',
    end1: 'blames his tools',
    end2: 'blame their tools',
  },
  {
    start1: 'A bird in the hand',
    start2: '',
    end1: 'is worth two in the bush',
    end2: 'are worth two in the bush',
  },
  {
    start1: 'A cat',
    start2: '',
    end1: 'may look at a king',
    end2: 'may look at a king',
  },
  {
    start1: 'A cat',
    start2: '',
    end1: 'has nine lives',
    end2: 'have nine lives',
  },
  {
    start1: 'A chain',
    start2: '',
    end1: 'is only as strong as its weakest link',
    end2: 'are only as strong as their weakest link',
  },
  {
    start1: 'A change',
    start2: '',
    end1: 'is as good as a rest',
    end2: 'are as good as a rest',
  },
  {
    start1: "A child that's born on the Sabbath day",
    start2: '',
    end1: 'is fair and wise and good and gay',
    end2: '',
  },
  {
    start1: 'A dog',
    start2: '',
    end1: "is a man's best friend",
    end2: "are a man's best friend",
  },
  {
    start1: 'A drowning man',
    start2: '',
    end1: 'will clutch at a straw',
    end2: 'will clutch at a straw',
  },
  {
    start1: 'A free lunch',
    start2: '',
    end1: '',
    end2: '',
  },
  {
    start1: 'A friend in need',
    start2: '',
    end1: 'is a friend indeed',
    end2: 'are a friend indeed',
  },
  {
    start1: 'A friend to everybody',
    start2: '',
    end1: 'is a friend to nobody',
    end2: 'are a friend to nobody',
  },
  {
    start1: 'A friend who shares',
    start2: '',
    end1: 'is a friend who cares',
    end2: '',
  },
  {
    start1: "A friend's frown",
    start2: '',
    end1: "is better than a fool's smile",
    end2: "are better than a fool's smile",
  },
  {
    start1: 'A gentle answer',
    start2: '',
    end1: 'turns away wrath',
    end2: 'turn away wrath',
  },
  {
    start1: 'A golden key',
    start2: '',
    end1: 'can open any door',
    end2: 'can open any door',
  },
  {
    start1: 'A good beginning',
    start2: '',
    end1: 'makes a good ending',
    end2: 'make a good ending',
  },
  {
    start1: 'A good conscience',
    start2: '',
    end1: 'is a soft pillow',
    end2: 'are a soft pillow',
  },
  {
    start1: 'A good husband',
    start2: '',
    end1: 'makes a good wife',
    end2: 'make good wives',
  },
  {
    start1: 'A good man',
    start2: '',
    end1: 'is hard to find',
    end2: 'are hard to find',
  },
  {
    start1: 'A good thing',
    start2: '',
    end1: 'is soon snatched up',
    end2: 'are soon snatched up',
  },
  {
    start1: 'A harsh word',
    start2: '',
    end1: 'stirs up anger',
    end2: 'stir up anger',
  },
  {
    start1: 'A house divided against itself',
    start2: '',
    end1: 'cannot stand',
    end2: 'cannot stand',
  },
  {
    start1: 'A leopard',
    start2: '',
    end1: "can't change its spots",
    end2: "can't change their spots",
  },
  {
    start1: 'A little knowledge',
    start2: '',
    end1: 'is a dangerous thing',
    end2: 'are a dangerous thing',
  },
  {
    start1: 'A loveless life',
    start2: '',
    end1: 'is a living death',
    end2: 'are a living death',
  },
  {
    start1: 'A man',
    start2: '',
    end1: 'is known by the company he keeps',
    end2: 'are known by the company they keep',
  },
  {
    start1: 'A miss',
    start2: '',
    end1: 'is as good as a mile',
    end2: 'are as good as a mile',
  },
  {
    start1: 'A nod',
    start2: '',
    end1: 'is as good as a wink to a blind horse',
    end2: 'are as good as a wink to a blind horse',
  },
  {
    start1: 'A penny saved',
    start2: '',
    end1: 'is a penny earned',
    end2: 'are a penny earned',
  },
  {
    start1: 'A picture',
    start2: '',
    end1: 'is worth a thousand words',
    end2: 'are worth a thousand words',
  },
  {
    start1: 'A problem shared',
    start2: '',
    end1: 'is a problem halved',
    end2: 'are a problem halved',
  },
  {
    start1: 'A red sky at night',
    start2: '',
    end1: "is a shepherd's delight",
    end2: "are a shepherd's delight",
  },
  {
    start1: 'A red sky in the morning',
    start2: '',
    end1: "is a shepherd's warning",
    end2: "are a shepherd's warning",
  },
  {
    start1: 'A rising tide',
    start2: '',
    end1: 'lifts all boats',
    end2: 'lift all boats',
  },
  {
    start1: 'A rolling stone',
    start2: '',
    end1: 'gathers no moss',
    end2: 'gather no moss',
  },
  {
    start1: 'A stitch in time',
    start2: '',
    end1: 'saves nine',
    end2: 'save nine',
  },
  {
    start1: 'A spoonful of sugar',
    start2: '',
    end1: 'helps the medicine go down',
    end2: 'help the medicine go down',
  },
  {
    start1: 'A thing of beauty',
    start2: '',
    end1: 'is a joy forever',
    end2: 'are a joy forever',
  },
  {
    start1: 'A throne',
    start2: '',
    end1: 'is only a bench covered in velvet',
    end2: 'are only a bench covered in velvet',
  },
  {
    start1: 'A volunteer',
    start2: '',
    end1: 'is worth twenty pressed men',
    end2: 'are worth twenty pressed men',
  },
  {
    start1: 'A watched pot',
    start2: '',
    end1: 'never boils',
    end2: 'never boil',
  },
  {
    start1: "A woman's place",
    start2: '',
    end1: 'is in the home',
    end2: 'are in the home',
  },
  {
    start1: "A woman's work",
    start2: '',
    end1: 'is never done',
    end2: 'are never done',
  },
  {
    start1: 'A word to the wise',
    start2: '',
    end1: '',
    end2: '',
  },
  {
    start1: 'Absence',
    start2: '',
    end1: 'makes the heart grow fonder',
    end2: 'make the heart grow fonder',
  },
  {
    start1: 'Power corrupts; absolute power',
    start2: '',
    end1: 'corrupts absolutely',
    end2: 'corrupt absolutely',
  },
  {
    start1: 'Adversity',
    start2: '',
    end1: 'makes strange bedfellows',
    end2: 'make strange bedfellows',
  },
  {
    start1: 'All publicity',
    start2: '',
    end1: 'is good publicity',
    end2: 'are good publicity',
  },
  {
    start1: 'All that glitters',
    start2: '',
    end1: 'is not gold',
    end2: 'are not gold',
  },
  {
    start1: 'All the world',
    start2: '',
    end1: 'loves a lover',
    end2: 'love a lover',
  },
  {
    start1: 'All work and no play',
    start2: '',
    end1: 'makes Jack a dull boy',
    end2: 'make Jack a dull boy',
  },
  {
    start1: 'All you need',
    start2: '',
    end1: 'is love',
    end2: 'are love',
  },
  {
    start1: 'An apple a day',
    start2: '',
    end1: 'keeps the doctor away',
    end2: 'keep the doctor away',
  },
  {
    start1: 'An army',
    start2: '',
    end1: 'marches on its stomach',
    end2: 'march on their stomach',
  },
  {
    start1: 'An elephant',
    start2: '',
    end1: 'never forgets',
    end2: 'never forget',
  },
  {
    start1: 'An empty barrel',
    start2: '',
    end1: 'makes the most noise',
    end2: 'make the most noise',
  },
  {
    start1: "An Englishman's home",
    start2: '',
    end1: 'is his castle',
    end2: 'are their castle',
  },
  {
    start1: 'An onion a day',
    start2: '',
    end1: 'keeps everyone away',
    end2: 'keep everyone away',
  },
  {
    start1: 'An ounce of prevention',
    start2: '',
    end1: 'is worth a pound of cure',
    end2: 'are worth a pound of cure',
  },
  {
    start1: 'Attack',
    start2: '',
    end1: 'is the best form of defence',
    end2: 'are the best form of defence',
  },
  {
    start1: 'Beauty',
    start2: '',
    end1: 'is in the eye of the beholder',
    end2: 'are in the eye of the beholder',
  },
  {
    start1: 'Beauty',
    start2: '',
    end1: 'is only skin deep',
    end2: 'are only skin deep',
  },
  {
    start1: 'Blood',
    start2: '',
    end1: 'is thicker than water',
    end2: 'are thicker than water',
  },
  {
    start1: 'Bread',
    start2: '',
    end1: 'always falls buttered side down',
    end2: 'always fall buttered side down',
  },
  {
    start1: 'Brevity',
    start2: '',
    end1: 'is the soul of wit',
    end2: 'are the soul of wit',
  },
  {
    start1: 'Charity',
    start2: '',
    end1: 'begins at home',
    end2: 'begin at home',
  },
  {
    start1: 'Cleanliness',
    start2: '',
    end1: 'is next to godliness',
    end2: 'are next to godliness',
  },
  {
    start1: 'Crime',
    start2: '',
    end1: "doesn't pay",
    end2: "don't pay",
  },
  {
    start1: 'Crying over spilt milk',
    start2: '',
    end1: 'is no use',
    end2: 'are no use',
  },
  {
    start1: 'Curiosity',
    start2: '',
    end1: 'killed the cat',
    end2: 'killed the cat',
  },
  {
    start1: 'Diligence',
    start2: '',
    end1: 'is the mother of good luck',
    end2: 'are the mother of good luck',
  },
  {
    start1: 'Discretion',
    start2: '',
    end1: 'is the better part of valour',
    end2: 'are the better part of valour',
  },
  {
    start1: "Don't bite the hand that",
    start2: '',
    end1: '',
    end2: '',
  },
  {
    start1: 'Erring',
    start2: '',
    end1: 'is human',
    end2: '',
  },
  {
    start1: 'Every cloud',
    start2: '',
    end1: 'has a silver lining',
    end2: 'have a silver lining',
  },
  {
    start1: 'Every dog',
    start2: '',
    end1: 'has its day',
    end2: 'have their day',
  },
  {
    start1: 'Every man',
    start2: '',
    end1: 'is the architect of his destiny',
    end2: 'are the architect of their destiny',
  },
  {
    start1: 'Every man',
    start2: '',
    end1: 'has his price',
    end2: 'have their price',
  },
  {
    start1: 'Every picture',
    start2: '',
    end1: 'tells a story',
    end2: 'tell a story',
  },
  {
    start1: 'Experience',
    start2: '',
    end1: 'is the father of wisdom',
    end2: 'are the father of wisdom',
  },
  {
    start1: 'Failing to plan',
    start2: '',
    end1: 'is planning to fail',
    end2: 'are planning to fail',
  },
  {
    start1: 'Faint heart',
    start2: '',
    end1: 'never won fair lady',
    end2: 'never won fair ladies',
  },
  {
    start1: 'Fair exchange',
    start2: '',
    end1: 'is no robbery',
    end2: 'are no robbery',
  },
  {
    start1: 'Faith',
    start2: '',
    end1: 'will move mountains',
    end2: 'will move no mountains',
  },
  {
    start1: 'Familiarity',
    start2: '',
    end1: 'breeds contempt',
    end2: 'breed contempt',
  },
  {
    start1: 'Flattery',
    start2: '',
    end1: 'will get you nowhere',
    end2: 'will get you nowhere',
  },
  {
    start1: 'Fortune',
    start2: '',
    end1: 'favours the brave',
    end2: 'favour the brave',
  },
  {
    start1: "Friday's child",
    start2: '',
    end1: 'is loving and giving',
    end2: '',
  },
  {
    start1: 'Giving',
    start2: '',
    end1: 'is better than receiving',
    end2: 'are better than receiving',
  },
  {
    start1: 'Good talk',
    start2: '',
    end1: 'saves the food',
    end2: 'save the food',
  },
  {
    start1: 'Half a loaf',
    start2: '',
    end1: 'is better than no bread',
    end2: 'are better than no bread',
  },
  {
    start1: 'Handsome',
    start2: '',
    end1: 'is as handsome does',
    end2: 'are as handsome does',
  },
  {
    start1: 'He has enough who',
    start2: '',
    end1: 'is content',
    end2: 'are content',
  },
  {
    start1: 'He is rich who',
    start2: '',
    end1: 'is satisfied',
    end2: 'are satisfied',
  },
  {
    start1: 'He who fights and runs away',
    start2: '',
    end1: 'lives to fight another day',
    end2: 'live to fight another day',
  },
  {
    start1: 'He who hesitates',
    start2: '',
    end1: 'is lost',
    end2: 'are lost',
  },
  {
    start1: 'He who laughs last',
    start2: '',
    end1: 'laughs longest',
    end2: 'laugh longest',
  },
  {
    start1: 'He who lives by the sword',
    start2: '',
    end1: 'shall die by the sword',
    end2: 'shall die by the sword',
  },
  {
    start1: 'Hindsight',
    start2: '',
    end1: 'is always twenty-twenty',
    end2: 'are always twenty-twenty',
  },
  {
    start1: 'History',
    start2: '',
    end1: 'repeats itself',
    end2: '',
  },
  {
    start1: 'Home',
    start2: '',
    end1: 'is where the heart is',
    end2: 'are where the heart is',
  },
  {
    start1: 'Honesty',
    start2: '',
    end1: 'is the best policy',
    end2: 'are the best policy',
  },
  {
    start1: 'If a job is worth doing it',
    start2: '',
    end1: 'is worth doing well',
    end2: 'are worth doing well',
  },
  {
    start1: 'Ignorance',
    start2: '',
    end1: 'is bliss',
    end2: 'are bliss',
  },
  {
    start1: 'Imitation',
    start2: '',
    end1: 'is the sincerest form of flattery',
    end2: 'are the sincerest form of flattery',
  },
  {
    start1: 'In the kingdom of the blind, the one-eyed man',
    start2: '',
    end1: 'is king',
    end2: '',
  },
  {
    start1: 'It never rains, but it',
    start2: '',
    end1: 'pours',
    end2: 'pour',
  },
  {
    start1: 'Knowledge',
    start2: '',
    end1: 'is power',
    end2: 'are power',
  },
  {
    start1: 'Laughter',
    start2: '',
    end1: 'is the best medicine',
    end2: 'are the best medicine',
  },
  {
    start1: 'Life',
    start2: '',
    end1: 'begins at forty',
    end2: 'begin at forty',
  },
  {
    start1: '',
    start2: '',
    end1: 'is just a bowl of cherries',
    end2: 'are just a bowl of cherries',
  },
  {
    start1: '',
    start2: '',
    end1: "is like a box of chocolates. You never know what you're gonna get",
    end2: '',
  },
  {
    start1: '',
    start2: '',
    end1: "is what happens to you while you're busy making other plans",
    end2: '',
  },
  {
    start1: 'Lightning',
    start2: '',
    end1: 'never strikes twice',
    end2: 'never strike twice',
  },
  {
    start1: 'Lost time',
    start2: '',
    end1: 'is never found again',
    end2: 'are never found again',
  },
  {
    start1: 'Love',
    start2: '',
    end1: 'is blind',
    end2: 'are blind',
  },
  {
    start1: 'Misery',
    start2: '',
    end1: 'loves company',
    end2: 'love company',
  },
  {
    start1: "Monday's child",
    start2: '',
    end1: 'is fair of face',
    end2: '',
  },
  {
    start1: 'Money',
    start2: '',
    end1: 'talks',
    end2: '',
  },
  {
    start1: 'Money',
    start2: '',
    end1: "doesn't grow on trees",
    end2: "don't grow on trees",
  },
  {
    start1: '',
    start2: '',
    end1: 'makes the world go round',
    end2: 'make the world go round',
  },
  {
    start1: 'Money, money, money',
    start2: '',
    end1: "must be funny in the rich man's world",
    end2: "must be funny in the rich man's world",
  },
  {
    start1: '',
    start2: '',
    end1: "can't buy happiness",
    end2: "can't buy happiness",
  },
  {
    start1: '',
    start2: '',
    end1: "can't buy me love",
    end2: "can't buy me love",
  },
  {
    start1: 'Music',
    start2: '',
    end1: 'has charms to soothe the savage breast',
    end2: 'have charms to soothe the savage breast',
  },
  {
    start1: 'Necessity',
    start2: '',
    end1: 'is the mother of invention',
    end2: 'are the mothers of invention',
  },
  {
    start1: 'No good deed',
    start2: '',
    end1: 'goes unpunished',
    end2: 'go unpunished',
  },
  {
    start1: 'No man',
    start2: '',
    end1: 'is an island',
    end2: 'are islands',
  },
  {
    start1: 'No man',
    start2: '',
    end1: 'can serve two masters',
    end2: 'can serve two masters',
  },
  {
    start1: 'No news',
    start2: '',
    end1: 'is good news',
    end2: 'are good news',
  },
  {
    start1: 'One good turn',
    start2: '',
    end1: 'deserves another',
    end2: 'deserve another',
  },
  {
    start1: "One man's junk",
    start2: '',
    end1: "is another man's treasure",
    end2: "are another man's treasure",
  },
  {
    start1: "One man's meat",
    start2: '',
    end1: "is another man's poison",
    end2: "are another man's poison",
  },
  {
    start1: "One man's terrorist",
    start2: '',
    end1: "is another man's freedom fighter",
    end2: '',
  },
  {
    start1: 'One swallow',
    start2: '',
    end1: 'does not make a summer',
    end2: 'do not make a summer',
  },
  {
    start1: '',
    start2: '',
    end1: '',
    end2: '',
  },
  {
    start1: 'Opportunity',
    start2: '',
    end1: 'never knocks twice',
    end2: 'never knock twice',
  },
  {
    start1: 'Patience',
    start2: '',
    end1: 'is a virtue',
    end2: '',
  },
  {
    start1: 'Possession',
    start2: '',
    end1: 'is nine-tenths of the law',
    end2: 'are nine-tenths of the law',
  },
  {
    start1: 'Practice',
    start2: '',
    end1: 'makes perfect',
    end2: 'make perfect',
  },
  {
    start1: 'Pride',
    start2: '',
    end1: 'comes before a fall',
    end2: 'come before a fall',
  },
  {
    start1: 'Procrastination',
    start2: '',
    end1: 'is the thief of time',
    end2: 'are the thieves of time',
  },
  {
    start1: 'Revenge',
    start2: '',
    end1: 'is a dish best served cold',
    end2: 'are a dish best served cold',
  },
  {
    start1: 'Revenge',
    start2: '',
    end1: 'is sweet',
    end2: 'are sweet',
  },
  {
    start1: 'Rome',
    start2: '',
    end1: "wasn't built in a day",
    end2: "weren't built in a day",
  },
  {
    start1: "Saturday's child",
    start2: '',
    end1: 'works hard for its living',
    end2: '',
  },
  {
    start1: 'Seeing',
    start2: '',
    end1: 'is believing',
    end2: 'are believing',
  },
  {
    start1: 'Silence',
    start2: '',
    end1: 'is golden',
    end2: 'are golden',
  },
  {
    start1: 'Speak of the devil and he',
    start2: '',
    end1: 'is bound to appear',
    end2: 'are bound to appear',
  },
  {
    start1: 'Strike while the iron',
    start2: '',
    end1: 'is hot',
    end2: 'are hot',
  },
  {
    start1: 'Success has many fathers, while failure',
    start2: '',
    end1: 'is an orphan',
    end2: 'are orphans',
  },
  {
    start1: 'Talk',
    start2: '',
    end1: 'is cheap',
    end2: 'are cheap',
  },
  {
    start1: 'That which does not kill us',
    start2: '',
    end1: 'makes us stronger',
    end2: 'make us stronger',
  },
  {
    start1: 'The apple',
    start2: '',
    end1: "doesn't fall far from the tree",
    end2: "don't fall far from the tree",
  },
  {
    start1: 'The bottom line',
    start2: '',
    end1: 'is the bottom line',
    end2: 'are the bottom line',
  },
  {
    start1: 'The cake',
    start2: '',
    end1: 'is a lie',
    end2: 'are a lie',
  },
  {
    start1: 'The cobbler',
    start2: '',
    end1: 'always wears the worst shoes',
    end2: 'always wear the worst shoes',
  },
  {
    start1: 'The course of true love',
    start2: '',
    end1: 'never did run smooth',
    end2: 'never did run smooth',
  },
  {
    start1: 'The customer',
    start2: '',
    end1: 'is always right',
    end2: 'are always right',
  },
  {
    start1: 'The darkest hour',
    start2: '',
    end1: 'is just before the dawn',
    end2: 'are just before the dawn',
  },
  {
    start1: 'The devil',
    start2: '',
    end1: 'finds work for idle hands',
    end2: 'find work for idle hands',
  },
  {
    start1: 'The devil you know',
    start2: '',
    end1: "is better than the devil you don't",
    end2: '',
  },
  {
    start1: 'The early bird',
    start2: '',
    end1: 'catches the worm',
    end2: 'catch the worm',
  },
  {
    start1: 'The end',
    start2: '',
    end1: 'justifies the means',
    end2: 'justify the means',
  },
  {
    start1: 'The enemy of my enemy',
    start2: '',
    end1: 'is my friend',
    end2: '',
  },
  {
    start1: 'The forbidden fruit',
    start2: '',
    end1: 'is the sweetest fruit',
    end2: 'are the sweetest fruits',
  },
  {
    start1: 'The grass',
    start2: '',
    end1: 'is always greener on the other side',
    end2: 'are always greener on the other side',
  },
  {
    start1: 'The hand that rocks the cradle',
    start2: '',
    end1: 'rules the world',
    end2: 'rule the world',
  },
  {
    start1: 'The husband',
    start2: '',
    end1: 'is always the last to know',
    end2: 'are always the last to know',
  },
  {
    start1: 'The last straw',
    start2: '',
    end1: "breaks the camel's back",
    end2: "break the camel's back",
  },
  {
    start1: 'The longest journey',
    start2: '',
    end1: 'starts with a single step',
    end2: 'start with a single step',
  },
  {
    start1: 'The love of money',
    start2: '',
    end1: 'is the root of all evil',
    end2: 'are the root of all evil',
  },
  {
    start1: '',
    start2: '',
    end1: 'is a root of all kinds of evil',
    end2: '',
  },
  {
    start1: 'The pen',
    start2: '',
    end1: 'is mightier than the sword',
    end2: 'are mightier than the sword',
  },
  {
    start1: 'The pot',
    start2: '',
    end1: 'calls the kettle black',
    end2: 'call the kettle black',
  },
  {
    start1: 'The proof of the pudding',
    start2: '',
    end1: 'is in the eating',
    end2: 'are in the eating',
  },
  {
    start1: 'The proof',
    start2: '',
    end1: 'is in the pudding',
    end2: 'are in the pudding',
  },
  {
    start1: 'The road to hell',
    start2: '',
    end1: 'is paved with good intentions',
    end2: 'are paved with good intentions',
  },
  {
    start1: 'The second mouse',
    start2: '',
    end1: 'gets the cheese',
    end2: 'get the cheese',
  },
  {
    start1: 'The sleeping fox',
    start2: '',
    end1: 'catches no chickens',
    end2: 'catch no chickens',
  },
  {
    start1: 'The spirit is willing, but the flesh',
    start2: '',
    end1: 'is weak',
    end2: 'are weak',
  },
  {
    start1: 'The squeaky wheel',
    start2: '',
    end1: 'gets the grease',
    end2: 'get the grease',
  },
  {
    start1: 'The truth',
    start2: '',
    end1: 'will out',
    end2: '',
  },
  {
    start1: "The way to a man's heart",
    start2: '',
    end1: 'is through his stomach',
    end2: '',
  },
  {
    start1: 'The world',
    start2: '',
    end1: 'is your oyster',
    end2: 'are your oyster',
  },
  {
    start1: "Thursday's child",
    start2: '',
    end1: 'has far to go',
    end2: '',
  },
  {
    start1: 'Time',
    start2: '',
    end1: "flies when you're having fun",
    end2: '',
  },
  {
    start1: 'Tomorrow',
    start2: '',
    end1: 'is a new day',
    end2: 'are a new day',
  },
  {
    start1: 'Live for today, for tomorrow',
    start2: '',
    end1: 'never comes',
    end2: 'never come',
  },
  {
    start1: 'True beauty',
    start2: '',
    end1: 'lies within',
    end2: 'lie within',
  },
  {
    start1: 'Truth',
    start2: '',
    end1: 'is stranger than fiction',
    end2: 'are stranger than fiction',
  },
  {
    start1: "Tuesday's child",
    start2: '',
    end1: 'is full of grace',
    end2: '',
  },
  {
    start1: 'Two is company, but three',
    start2: '',
    end1: 'is company, but three is a crowd',
    end2: 'are company, but three is a crowd',
  },
  {
    start1: 'Variety',
    start2: '',
    end1: 'is the spice of life',
    end2: 'are the spice of life',
  },
  {
    start1: 'Virtue',
    start2: '',
    end1: 'is its own reward',
    end2: '',
  },
  {
    start1: "Wednesday's child",
    start2: '',
    end1: 'is full of woe',
    end2: '',
  },
  {
    start1: "What can't be cured",
    start2: '',
    end1: 'must be endured',
    end2: 'must be endured',
  },
  {
    start1: 'What goes up',
    start2: '',
    end1: 'must come down',
    end2: 'must come down',
  },
  {
    start1: "What's good for the goose",
    start2: '',
    end1: 'is good for the gander',
    end2: 'are good for the gander',
  },
  {
    start1: "What doesn't kill you",
    start2: '',
    end1: 'makes you stronger',
    end2: '',
  },
  {
    start1: 'What happens in Vegas',
    start2: '',
    end1: 'stays in Vegas',
    end2: '',
  },
  {
    start1: 'What you see',
    start2: '',
    end1: 'is what you get',
    end2: '',
  },
  {
    start1: 'Who dares',
    start2: '',
    end1: 'wins',
    end2: 'win',
  },
  {
    start1: 'Worrying',
    start2: '',
    end1: 'never did anyone any good',
    end2: 'never did anyone any good',
  },
  {
    start1: 'Youth',
    start2: '',
    end1: 'is wasted on the young',
    end2: 'are wasted on the young',
  },
  {
    start1: '',
    start2: '',
    end1: 'is the new black',
    end2: 'are the new black',
  },
  {
    start1: '',
    start2: '',
    end1: 'is fair in love and war',
    end2: 'are fair in love and war',
  },
  {
    start1: '',
    start2: '',
    end1: 'cannot live by bread alone',
    end2: 'cannot live by bread alone',
  },
  {
    start1: '',
    start2: '',
    end1: 'makes a man healthy, wealthy and wise',
    end2: 'make a man healthy, wealthy and wise',
  },
  {
    start1: '',
    start2: '',
    end1: 'is well that ends well',
    end2: 'are well that end well',
  },
  {
    start1: '',
    start2: '',
    end1: 'is what you make it',
    end2: 'are what you make them',
  },
  {
    start1: 'A journey of a thousand miles',
    start2: '',
    end1: 'begins with a single step',
    end2: 'begin with a single step',
  },
  {
    start1: 'A man with a hammer',
    start2: '',
    end1: 'sees every problem as a nail',
    end2: 'see every problem as a nail',
  },
  {
    start1: 'A man who is his own lawyer',
    start2: '',
    end1: 'has a fool for a client',
    end2: 'have a fool for a client',
  },
  {
    start1: 'Careless talk',
    start2: '',
    end1: 'costs lives',
    end2: 'cost lives',
  },
  {
    start1: 'Courage is the measure of a man, beauty',
    start2: '',
    end1: 'is the measure of a woman',
    end2: 'are the measure of a woman',
  },
  {
    start1: '',
    start2: '',
    end1: "shouldn't bite the hand that feeds you",
    end2: "shouldn't bite the hand that feeds them",
  },
  {
    start1: '',
    start2: '',
    end1: "shouldn't cry over spilt milk",
    end2: "shouldn't cry over spilt milk",
  },
  {
    start1: '',
    start2: '',
    end1: "shouldn't count your chickens before they are hatched",
    end2: "shouldn't count their chickens before they are hatched",
  },
  {
    start1: '',
    start2: '',
    end1: "shouldn't cross the bridge till you come to it",
    end2: "shouldn't cross the bridge till they come to it",
  },
  {
    start1: '',
    start2: '',
    end1: "shouldn't cut off your nose to spite your face",
    end2: "shouldn't cut off their nose to spite their face",
  },
  {
    start1: '',
    start2: '',
    end1: '',
    end2: "shouldn't keep a dog and bark themselves",
  },
  {
    start1: '',
    start2: '',
    end1: 'should never look a gift horse in the mouth',
    end2: 'should never look a gift horse in the mouth',
  },
  {
    start1: '',
    start2: '',
    end1: '',
    end2: "shouldn't put all their eggs in one basket",
  },
  {
    start1: '',
    start2: '',
    end1: "shouldn't rock the boat",
    end2: "shouldn't rock the boat",
  },
  {
    start1: '',
    start2: '',
    end1: '',
    end2: "can't walk before they can crawl",
  },
  {
    start1: 'Doubt',
    start2: '',
    end1: 'is the beginning of wisdom',
    end2: 'are the beginning of wisdom',
  },
  {
    start1: '',
    start2: '',
    end1: 'is enough',
    end2: 'are enough',
  },
  {
    start1: 'The fear of the Lord',
    start2: '',
    end1: 'is the beginning of wisdom',
    end2: 'are the beginning of wisdom',
  },
  {
    start1: 'East is east, and west',
    start2: '',
    end1: '',
    end2: '',
  },
  {
    start1: '',
    start2: '',
    end1: '',
    end2: 'rush in where angels fear to tread',
  },
  {
    start1: 'Give him an inch and he',
    start2: '',
    end1: 'will take a mile',
    end2: 'will take a mile',
  },
  {
    start1: 'Give a man a fish and he',
    start2: '',
    end1: 'will eat for a day',
    end2: 'will eat for a day',
  },
  {
    start1: 'Give a man a fish and he will eat for a day; teach him to fish and he',
    start2: '',
    end1: 'will eat for a lifetime',
    end2: 'will eat for a lifetime',
  },
  {
    start1: 'Give a man enough rope and he',
    start2: '',
    end1: 'will hang himself',
    end2: 'will hang themselves',
  },
  {
    start1: 'He that goes a-borrowing,',
    start2: '',
    end1: 'goes a-sorrowing',
    end2: 'go a-sorrowing',
  },
  {
    start1: 'He who pays the piper',
    start2: '',
    end1: 'calls the tune',
    end2: 'call the tune',
  },
  {
    start1: 'He who knows, does not speak. He who speaks,',
    start2: '',
    end1: 'does not know',
    end2: 'do not know',
  },
  {
    start1: 'Hell',
    start2: '',
    end1: 'hath no fury like a woman scorned',
    end2: 'have no fury like a woman scorned',
  },
  {
    start1: 'If anything can go wrong, it',
    start2: '',
    end1: '',
    end2: '',
  },
  {
    start1: '',
    start2: 'If you pay peanuts, you',
    end1: 'gets monkeys',
    end2: 'get monkeys',
  },
  {
    start1: '',
    start2: 'When life gives you lemons, you',
    end1: 'makes lemonade',
    end2: 'make lemonade',
  },
  {
    start1: '',
    start2: "If you can't stand the heat, you",
    end1: 'gets out of the kitchen',
    end2: 'get out of the kitchen',
  },
  {
    start1: 'Knowledge is power, France',
    start2: '',
    end1: 'is bacon',
    end2: 'are bacon',
  },
  {
    start1: '',
    start2: 'Laugh and the world laughs with you; weep and you',
    end1: 'weeps alone',
    end2: 'weep alone',
  },
  {
    start1: 'Many a true word',
    start2: '',
    end1: 'is spoken in jest',
    end2: 'are spoken in jest',
  },
  {
    start1: '',
    start2: '',
    end1: 'comes in like a lion and goes out like a lamb',
    end2: 'come in like a lion and go out like a lamb',
  },
  {
    start1: 'March comes in like a lion and',
    start2: '',
    end1: 'goes out like a lamb',
    end2: 'go out like a lamb',
  },
  {
    start1: 'The rain in Spain',
    start2: '',
    end1: 'falls mainly on the plain',
    end2: 'fall mainly on the plain',
  },
  {
    start1: 'When clouds look like black smoke, a wise man',
    start2: '',
    end1: 'will put on his cloak',
    end2: '',
  },
  {
    start1: 'When one door closes, another door',
    start2: '',
    end1: '',
    end2: '',
  },
  {
    start1: 'Nature',
    start2: '',
    end1: 'abhors a vacuum',
    end2: 'abhor a vacuum',
  },
  {
    start1: '',
    start2: '',
    end1: 'should never judge a book by its cover',
    end2: 'should never judge a book by its cover',
  },
  {
    start1: '',
    start2: '',
    end1: 'should never say never',
    end2: 'should never say never',
  },
  {
    start1: '',
    start2: '',
    end1: 'is certain, except death and taxes',
    end2: '',
  },
  {
    start1: 'One hand',
    start2: '',
    end1: 'washes the other',
    end2: '',
  },
  {
    start1: 'Slow and steady',
    start2: '',
    end1: 'wins the race',
    end2: 'win the race',
  },
  {
    start1: 'Stupid',
    start2: '',
    end1: 'is as stupid does',
    end2: '',
  },
  {
    start1: '',
    start2: 'If you spare the rod, you',
    end1: '',
    end2: 'spoil the child',
  },
  {
    start1: '',
    start2: 'Take care of the pence, and the pounds',
    end1: '',
    end2: 'will take care of themselves',
  },
  {
    start1: 'The best defence',
    start2: '',
    end1: 'is a good offence',
    end2: 'are a good offence',
  },
  {
    start1: '',
    start2: '',
    end1: 'is money',
    end2: 'are money',
  },
  {
    start1: '',
    start2: '',
    end1: 'is born every minute',
    end2: 'are born every minute',
  },
  {
    start1: 'Hatred',
    start2: '',
    end1: 'is as blind as love',
    end2: 'are as blind as love',
  },
  {
    start1: 'God',
    start2: '',
    end1: 'loves a cheerful giver',
    end2: '',
  },
  {
    start1: '',
    start2: '',
    end1: 'is a thin line between love and hate',
    end2: '',
  },
  {
    start1: 'No man or woman is worth your tears, and the one who is',
    start2: '',
    end1: "won't make you cry",
    end2: "won't make you cry",
  },
  {
    start1: 'A bully',
    start2: '',
    end1: 'is always a coward',
    end2: 'are always a coward',
  },
  {
    start1: 'A handsome shoe',
    start2: '',
    end1: 'often pinches the foot',
    end2: 'often pinch the foot',
  },
  {
    start1: '',
    start2: '',
    end1: '',
    end2: 'are what you eat',
  },
  {
    start1: 'No wise man',
    start2: '',
    end1: 'wishes to be younger',
    end2: '',
  },
  {
    start1: '',
    start2: '',
    end1: 'is worse than his bite',
    end2: 'are worse than his bite',
  },
  {
    start1: 'Make hay while the sun',
    start2: '',
    end1: '',
    end2: '',
  },
  {
    start1: 'A small spark',
    start2: '',
    end1: 'can start a great fire',
    end2: 'can start a great fire',
  },
  {
    start1: 'A single penny, fairly got,',
    start2: '',
    end1: 'is worth a thousand that are not',
    end2: '',
  },
  {
    start1: '',
    start2: 'Diamonds',
    end1: "is a girl's best friend",
    end2: "are a girl's best friend",
  },
  {
    start1: '',
    start2: '',
    end1: 'burns a hole in your pocket',
    end2: 'burn a hole in your pocket',
  },
  {
    start1: '',
    start2: 'Rules',
    end1: 'is made to be broken',
    end2: 'are made to be broken',
  },
  {
    start1: 'He who can, does. He who cannot,',
    start2: 'Those who can, do. Those who cannot,',
    end1: 'teaches',
    end2: 'teach',
  },
  {
    start1: 'A verbal contract',
    start2: 'Verbal contracts',
    end1: "isn't worth the paper it's written on",
    end2: "aren't worth the paper they're written on",
  },
  {
    start1: '',
    start2: 'All cats',
    end1: '',
    end2: 'love fish but hate to get their paws wet',
  },
  {
    start1: 'Ask me no questions, I',
    start2: '',
    end1: 'will tell you no lies',
    end2: 'will tell you no lies',
  },
  {
    start1: 'A broken clock',
    start2: '',
    end1: 'is right two times a day',
    end2: 'are right two times a day',
  },
  {
    start1: 'The calm',
    start2: '',
    end1: 'comes before the storm',
    end2: 'come before the storm',
  },
  {
    start1: '',
    start2: 'Desperate times',
    end1: 'calls for desperate measures',
    end2: 'call for desperate measures',
  },
  {
    start1: 'Every rose',
    start2: '',
    end1: 'has its thorn',
    end2: '',
  },
  {
    start1: 'The exception',
    start2: '',
    end1: 'proves the rule',
    end2: '',
  },
  {
    start1: 'Fifty percent of something',
    start2: '',
    end1: 'is better than one hundred percent of nothing',
    end2: '',
  },
  {
    start1: '',
    start2: 'Fine words',
    end1: 'butters no parsnips',
    end2: 'butter no parsnips',
  },
  {
    start1: '',
    start2: '',
    end1: "ain't broke, don't fix it",
    end2: '',
  },
  {
    start1: '',
    start2: '',
    end1: 'seems to good to be true, it probably is',
    end2: '',
  },
  {
    start1: '',
    start2: 'If wishes were horses, beggars',
    end1: '',
    end2: 'would ride',
  },
  {
    start1: '',
    start2: "If you aren't part of the solution, you",
    end1: '',
    end2: 'are part of the problem',
  },
  {
    start1: '',
    start2: '',
    end1: "isn't over until the fat lady sings",
    end2: '',
  },
  {
    start1: 'Insanity',
    start2: '',
    end1: 'is doing the same thing over and over, and expecting different results',
    end2: '',
  },
  {
    start1: '',
    start2: '',
    end1: 'is always darkest before the dawn',
    end2: '',
  },
  {
    start1: '',
    start2: '',
    end1: 'is better to be silent and thought a fool, than to speak up and remove all doubt',
    end2: '',
  },
  {
    start1: 'A lie can be halfway around the world before the truth',
    start2: '',
    end1: 'gets its boots on',
    end2: '',
  },
  {
    start1: '',
    start2: 'The more things change, the more they',
    end1: '',
    end2: 'stay the same',
  },
  {
    start1: '',
    start2: 'There are none so blind as they who',
    end1: '',
    end2: 'will not see',
  },
  {
    start1: 'One rotten apple',
    start2: '',
    end1: 'will spoil the whole barrel',
    end2: '',
  },
  {
    start1: '',
    start2: 'Smile, and the world smiles with you; cry, and you',
    end1: '',
    end2: 'cry alone',
  },
  {
    start1: 'Smile, and the world',
    start2: '',
    end1: 'smiles with you; cry, and you cry alone',
    end2: '',
  },
  {
    start1: '',
    start2: 'This, too,',
    end1: 'shall pass',
    end2: '',
  },
  {
    start1: '',
    start2: '',
    end1: 'has nothing to fear but fear itself',
    end2: 'have nothing to fear but fear itself',
  },
  {
    start1: 'A woman',
    start2: '',
    end1: "is like a tea bag; you'll never know how strong she is until she's in hot water",
    end2: '',
  },
  {
    start1: 'As a dog returns to his vomit, so a fool',
    start2: '',
    end1: 'returns to his folly',
    end2: '',
  },
  {
    start1: '',
    start2: 'Finders keepers; losers',
    end1: '',
    end2: '',
  },
  {
    start1: '',
    start2: '',
    end1: 'is one percent inspiration, ninety-nine percent perspiration',
    end2: '',
  },
  {
    start1: 'Honey',
    start2: '',
    end1: 'catches more flies than vinegar',
    end2: '',
  },
  {
    start1: 'Justice delayed',
    start2: '',
    end1: 'is justice denied',
    end2: '',
  },
  {
    start1: '',
    start2: 'Snitches',
    end1: '',
    end2: 'get stitches',
  },
  {
    start1: '',
    start2: 'The best laid plans of mice and men',
    end1: '',
    end2: 'often go awry',
  },
  {
    start1: '',
    start2: 'The bigger they are, the harder they',
    end1: '',
    end2: '',
  },
];

const start1: string[] = [],
  start2: string[] = [],
  end1: string[] = [],
  end2: string[] = [];

idioms.forEach((idiom: IdiomSet) => {
  idiom.start1 && start1.push(idiom.start1);
  idiom.start2 && start2.push(idiom.start2);
  idiom.end1 && end1.push(idiom.end1);
  idiom.end2 && end2.push(idiom.end2);
});

// decide on singular or plural
const choosePlural = (): boolean => {
  const ratioSingularToPlural = 4;
  const flip = Math.floor(Math.random() * (ratioSingularToPlural + 1));
  if (flip === 1) {
    return true;
  }
  return false;
};

// choose a random element from an array
const randomFromArray = (arr: string[]): string => {
  return arr[Math.floor(Math.random() * arr.length)];
};

// generate an idiom
export const generateIdiom = (): string => {
  const plural = choosePlural();
  return plural
    ? `${randomFromArray(start2)} ${randomFromArray(end2)}.`
    : `${randomFromArray(start1)} ${randomFromArray(end1)}.`;
};
